keys:
  # users
  - &users:
    - &gabe age1yscg86yrkxlt6xj4gnmw5l98xwajwph36ye2u5ltfyts3h6kh9dqcs83zj
    - &gha_flake age1k8v5vq6uv8vjh6alyrzd6y44fq8l8exkqp4es5seef5muqauv5hqkcgk29
  # hosts
  - &hosts:
    - &bastion age1wdy8dlkhxmxgqqfzjqg9e2jz40qkmp9pkvshzxvzz8ytwa255eqqnl2fcs
    - &voyager age1f5xlnwk04z727lca79ur6lwk2sv82fwgrzg4x6xtcq7s7uw2r4rsqhxm9r
    - &quasar age19ke07grxa0eshd3eqhgrahua90yslcdw4ecktsdtcpwd7mw98duszff9x0
    - &deck age1yn0dnu32zfw05e4vazgpa0yxj3r8208hqa02sv8hdsfkg0fd83tqaflsym

creation_rules:
  - path_regex: hosts/common/secrets\.(ya?ml|json|env|ini)$
    key_groups:
      - age:
          - *gabe
          - *bastion
          - *voyager
          - *quasar
          - *deck

  - path_regex: hosts/bastion/secrets\.(ya?ml|json|env|ini)$
    key_groups:
      - age:
          - *gabe
          - *bastion

  - path_regex: hosts/voyager/secrets\.(ya?ml|json|env|ini)$
    key_groups:
      - age:
          - *gabe
          - *voyager

  - path_regex: hosts/quasar/secrets\.(ya?ml|json|env|ini)$
    key_groups:
      - age:
          - *gabe
          - *quasar

  - path_regex: hosts/deck/secrets\.(ya?ml|json|env|ini)$
    key_groups:
      - age:
          - *gabe
          - *deck

  - path_regex: home/gabe/secrets\.(ya?ml|json|env|ini)$
    key_groups:
      - age:
          - *gabe
          - *gha_flake
