[project]
name = "nixfiles"
revision = "1.0"

[profiles.default]
# DATABASE_URL = { description = "Database connection string", required = true }
TAILSCALE_API_KEY = { description = "Tailscale API key", required = false }
