[profile]
name = "Deadlock"
enabled = true
is_permanent = false
priority = 4
notify_on_activation = false
created_at = "2026-09-16T13:49:47.438120"
window_rules = [
    { field = "class", pattern = "steam_app_1422450" },
    { field = "title", pattern = "Deadlock" },
]

[devices."046d:4085"]
always_grab_all = false

[devices."046d:4085".mapping.key_f14]
action = "keyboard"
target = "key_e"

[devices."046d:4085".mapping.key_f17]
action = "keyboard"
target = "key_r"

[devices."046d:4085".mapping.key_f15]
action = "keyboard"
target = "key_4"

[devices."046d:4085".mapping.key_f13]
action = "keyboard"
target = "key_1"
