enabled = true
schema_version = 2
widget_order = ["lockscreen-login-box@DP-2", "lockscreen-login-box@DP-1", "lockscreen-widget-0000000000000001", "lockscreen-widget-0000000000000004", "lockscreen-widget-0000000000000005", "lockscreen-widget-0000000000000006", "lockscreen-widget-0000000000000007", "lockscreen-widget-0000000000000008", "lockscreen-widget-0000000000000009", "lockscreen-widget-000000000000000a"]

[grid]
cell_size = 16
major_interval = 4
visible = true

[widget."lockscreen-login-box@DP-1"]
box_height = 80.0
box_width = 912.0
cx = 1280.0
cy = 1320.0
output = "DP-1"
rotation = 0.0
type = "login_box"

[widget."lockscreen-login-box@DP-1".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
input_opacity = 1.0
input_radius = 6.0
show_login_button = true

[widget."lockscreen-login-box@DP-2"]
box_height = 70.0
box_width = 400.0
cx = 1280.0
cy = 1321.0
output = "DP-2"
rotation = 0.0
type = "login_box"

[widget."lockscreen-login-box@DP-2".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
input_opacity = 1.0
input_radius = 6.0
show_login_button = true

[widget.lockscreen-widget-0000000000000001]
box_height = 128.0
box_width = 240.0
cx = 1280.0
cy = 208.0
output = "DP-1"
rotation = 0.0
type = "clock"

[widget.lockscreen-widget-0000000000000001.settings]
center_text = true
clock_style = "digital"
format = "{:%H:%M:%S}"

[widget.lockscreen-widget-0000000000000004]
box_height = 256.0
box_width = 320.0
cx = 1576.0
cy = 1104.0
output = "DP-1"
rotation = 0.0
type = "fancy_audio_visualizer"

[widget.lockscreen-widget-0000000000000004.settings]
background = true
visualization_mode = "bars_rings"

[widget.lockscreen-widget-0000000000000005]
box_height = 256.0
box_width = 576.0
cx = 1112.0
cy = 1104.0
output = "DP-1"
rotation = 0.0
type = "media_player"

[widget.lockscreen-widget-0000000000000006]
box_height = 80.0
box_width = 208.0
cx = 928.0
cy = 912.0
output = "DP-1"
rotation = 0.0
type = "button"

[widget.lockscreen-widget-0000000000000006.settings]
background = true
glyph = "logout"
label = "Logout"
variant = "default"

[widget.lockscreen-widget-0000000000000007]
box_height = 96.0
box_width = 176.0
cx = 1280.0
cy = 336.0
output = "DP-1"
rotation = 0.0
type = "weather"

[widget.lockscreen-widget-0000000000000007.settings]
background = true
shadow = true
show_forecast = false

[widget.lockscreen-widget-0000000000000008]
box_height = 80.0
box_width = 208.0
cx = 1160.0
cy = 912.0
output = "DP-1"
rotation = 0.0
type = "button"

[widget.lockscreen-widget-0000000000000008.settings]
background = true
glyph = "suspend"
label = "Suspend"
variant = "default"

[widget.lockscreen-widget-0000000000000009]
box_height = 80.0
box_width = 208.0
cx = 1400.0
cy = 912.0
output = "DP-1"
rotation = 0.0
type = "button"

[widget.lockscreen-widget-0000000000000009.settings]
background = true
glyph = "reboot"
label = "Reboot"
variant = "default"

[widget.lockscreen-widget-000000000000000a]
box_height = 80.0
box_width = 208.0
cx = 1632.0
cy = 912.0
output = "DP-1"
rotation = 0.0
type = "button"

[widget.lockscreen-widget-000000000000000a.settings]
background = true
color = "error"
command = ""
font_family = ""
glyph = "power"
hover_background = "hover"
label = "Shutdown"
variant = "default"
