name: "Nix Build Cache"
on:
  push:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check --print-build-logs

  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#devShells.x86_64-linux.default --print-build-logs --impure

  packages-beekeeper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#packages.x86_64-linux.beekeeper-studio-ultimate --print-build-logs

  packages-cockpit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#packages.x86_64-linux.cockpit-benchmark --print-build-logs
      - run: nix build .#packages.x86_64-linux.cockpit-docker --print-build-logs
      - run: nix build .#packages.x86_64-linux.cockpit-file-sharing --print-build-logs
      - run: nix build .#packages.x86_64-linux.cockpit-machines --print-build-logs
      - run: nix build .#packages.x86_64-linux.cockpit-tailscale --print-build-logs
      - run: nix build .#packages.x86_64-linux.cockpit-zfs-manager --print-build-logs

  packages-dashy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#packages.x86_64-linux.dashy --print-build-logs

  packages-seabird:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#packages.x86_64-linux.seabird --print-build-logs

  packages-switchup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#packages.x86_64-linux.switchup --print-build-logs
