name: "Nix build"
on:
  pull_request:
  push:
jobs:
  # checks:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: cachix/install-nix-action@v20
  #     - uses: cachix/cachix-action@v12
  #       with:
  #         name: gabedunn
  #         authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
  #     - run: nix flake check --print-build-logs --impure

  # shell:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: cachix/install-nix-action@v20
  #     - uses: cachix/cachix-action@v12
  #       with:
  #         name: gabedunn
  #         authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
  #     - run: nix build .#devShells.x86_64-linux.default --print-build-logs --impure

  # system & home configurations
  home-deck:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: gabedunn
          # If you chose signing key for write access
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build '.#homeConfigurations."gabe@deck".activationPackage' --print-build-logs

  packages-beekeeper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#packages.x86_64-linux.beekeeper-studio-ultimate --print-build-logs

  packages-cockpit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#packages.x86_64-linux.cockpit-benchmark --print-build-logs
      - run: nix build .#packages.x86_64-linux.cockpit-docker --print-build-logs
      - run: nix build .#packages.x86_64-linux.cockpit-file-sharing --print-build-logs
      - run: nix build .#packages.x86_64-linux.cockpit-machines --print-build-logs
      - run: nix build .#packages.x86_64-linux.cockpit-tailscale --print-build-logs
      - run: nix build .#packages.x86_64-linux.cockpit-zfs-manager --print-build-logs

  packages-dashy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#packages.x86_64-linux.dashy --print-build-logs

  packages-seabird:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#packages.x86_64-linux.seabird --print-build-logs

  packages-switchup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#packages.x86_64-linux.switchup --print-build-logs
