name: "Nix Build Cache"
on:
  push:
jobs:
  # checks:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Free Disk Space (Ubuntu)
  #       uses: jlumbroso/free-disk-space@main
  #       with:
  #         tool-cache: true
  #     - uses: actions/checkout@v4
  #     - uses: cachix/install-nix-action@v26
  #       with:
  #         nix_path: nixpkgs=channel:nixos-unstable
  #     - uses: cachix/cachix-action@v14
  #       with:
  #         name: gabedunn
  #         signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
  #         authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
  #     - run: nix flake check --print-build-logs

  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: gabedunn
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#devShells.x86_64-linux.default --print-build-logs --impure

  packages:
    strategy:
      matrix:
        package:
          - beekeeper-studio-ultimate
          - cockpit-benchmark
          - cockpit-docker
          - cockpit-file-sharing
          - cockpit-machines
          - cockpit-tailscale
          - cockpit-zfs-manager
          - dashy
          - seabird
          - switchup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v14
        with:
          name: gabedunn
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#packages.x86_64-linux.${{ matrix.package }} --print-build-logs
